name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clippy
        run: cargo clippy
      - name: Tests
        run: cargo test --all
      - name: Build
        run: cargo build --verbose
